// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdmnryyvrkrswveqebbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkbW5yeXl2cmtyc3d2ZXFlYmJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MDY3MjUsImV4cCI6MjA2MzQ4MjcyNX0.8v5lTH477hMsCQWOH1FM1yMfGnpphh_5Gg9oRPFBG2g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);